### health check
GET http://localhost:18080
Content-Type: application/json

### get
GET http://localhost:18080/todos/501d09e6-c484-47e3-941a-7496c61d224b
Accept: application/json

### list
GET http://localhost:18080/todos
Accept: application/json

### add
PUT http://localhost:18080/todos
Content-Type: application/json

{
  "title": "test title",
  "description": "test description"
}

### delete
DELETE http://localhost:18080/todos/2a7e1d52-d477-4326-be63-59c037e2f29a
Content-Type: application/json
